### ISSUE TITLE
Download the github files

### ISSUE THREAD

**Issue by RobertPomichter** [AngryRedAngler/COP4331-LargeProject#1]
I'd like to delete the environment variables from the github repo so they are not public. They are, after all, supposed to be secret. Please, clone the repo to your local machines at your earlieast convenience so you can work with the files and I can remove the .env file. Leave a comment in this issue thread when you have done so. If you are the last person to download the files then please close this issue with a comment. Thank you!

**Comment by RobertPomichter** [comment]
I have cloned the repo for myself.

**Comment by minifold** [comment]
I've cloned the repo as well

**Comment by maxgomer** [comment]
i've cloned the repo
